#!/usr/bin/env node
/**
 * Test balances with z2js
 *
 * Generated from solution JSON file
 * Commands: 486
 */

const { createZMachine } = require('./balances_z2js.js');

const commands = [
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "look",
    "examine matchwood",
    "examine lived",
    "examine extend",
    "examine day",
    "examine horizon",
    "examine feel",
    "examine glassless",
    "examine sunny",
    "examine warm",
    "examine someone",
    "take matchwood",
    "take lived",
    "take extend",
    "take day",
    "take horizon",
    "take feel",
    "take glassless",
    "take sunny",
    "take warm",
    "take someone",
    "open matchwood",
    "open lived",
    "open extend",
    "open day",
    "open horizon",
    "open feel",
    "open glassless",
    "open sunny",
    "open warm",
    "open someone",
    "read matchwood",
    "read lived",
    "read extend",
    "read day",
    "read horizon",
    "read feel",
    "read glassless",
    "read sunny",
    "read warm",
    "read someone",
    "move matchwood",
    "move lived",
    "move extend",
    "move day",
    "move horizon",
    "move feel",
    "move glassless",
    "move sunny",
    "move warm",
    "move someone",
    "push matchwood",
    "push lived",
    "push extend",
    "push day",
    "push horizon",
    "push feel",
    "push glassless",
    "push sunny",
    "push warm",
    "push someone",
    "pull matchwood",
    "pull lived",
    "pull extend",
    "pull day",
    "pull horizon",
    "pull feel",
    "pull glassless",
    "pull sunny",
    "pull warm",
    "pull someone",
    "turn matchwood",
    "turn lived",
    "turn extend",
    "turn day",
    "turn horizon",
    "turn feel",
    "turn glassless",
    "turn sunny",
    "turn warm",
    "turn someone",
    "light matchwood",
    "light lived",
    "light extend",
    "light day",
    "light horizon",
    "light feel",
    "light glassless",
    "light sunny",
    "light warm",
    "light someone",
    "look",
    "examine broken",
    "examine directions",
    "examine this",
    "examine sway",
    "examine peaceful",
    "examine faint",
    "examine grasslands",
    "examine north",
    "examine over",
    "examine hills",
    "take broken",
    "take directions",
    "take this",
    "take sway",
    "take peaceful",
    "take faint",
    "take grasslands",
    "take north",
    "take over",
    "take hills",
    "open broken",
    "open directions",
    "open this",
    "open sway",
    "open peaceful",
    "open faint",
    "open grasslands",
    "open north",
    "open over",
    "open hills",
    "read broken",
    "read directions",
    "read this",
    "read sway",
    "read peaceful",
    "read faint",
    "read grasslands",
    "read north",
    "read over",
    "read hills",
    "move broken",
    "move directions",
    "move this",
    "move sway",
    "move peaceful",
    "move faint",
    "move grasslands",
    "move north",
    "move over",
    "move hills",
    "push broken",
    "push directions",
    "push this",
    "push sway",
    "push peaceful",
    "push faint",
    "push grasslands",
    "push north",
    "push over",
    "push hills",
    "pull broken",
    "pull directions",
    "pull this",
    "pull sway",
    "pull peaceful",
    "pull faint",
    "pull grasslands",
    "pull north",
    "pull over",
    "pull hills",
    "turn broken",
    "turn directions",
    "turn this",
    "turn sway",
    "turn peaceful",
    "turn faint",
    "turn grasslands",
    "turn north",
    "turn over",
    "turn hills",
    "light broken",
    "light directions",
    "light this",
    "light sway",
    "light peaceful",
    "light faint",
    "light grasslands",
    "light north",
    "light over",
    "light hills",
    "look",
    "examine trail",
    "examine pile",
    "examine runs",
    "examine oats",
    "examine horse",
    "examine valley",
    "examine here",
    "examine munching",
    "examine pleasant",
    "take trail",
    "take pile",
    "take runs",
    "take oats",
    "take horse",
    "take valley",
    "take here",
    "take munching",
    "take pleasant",
    "open trail",
    "open pile",
    "open runs",
    "open oats",
    "open horse",
    "open valley",
    "open here",
    "open munching",
    "open pleasant",
    "read trail",
    "read pile",
    "read runs",
    "read oats",
    "read horse",
    "read valley",
    "read here",
    "read munching",
    "read pleasant",
    "move trail",
    "move pile",
    "move runs",
    "move oats",
    "move horse",
    "move valley",
    "move here",
    "move munching",
    "move pleasant",
    "push trail",
    "push pile",
    "push runs",
    "push oats",
    "push horse",
    "push valley",
    "push here",
    "push munching",
    "push pleasant",
    "pull trail",
    "pull pile",
    "pull runs",
    "pull oats",
    "pull horse",
    "pull valley",
    "pull here",
    "pull munching",
    "pull pleasant",
    "turn trail",
    "turn pile",
    "turn runs",
    "turn oats",
    "turn horse",
    "turn valley",
    "turn here",
    "turn munching",
    "turn pleasant",
    "light trail",
    "light pile",
    "light runs",
    "light oats",
    "light horse",
    "light valley",
    "light here",
    "light munching",
    "light pleasant"
];

async function test() {
    console.log('=' .repeat(60));
    console.log(' BALANCES: Z2JS ENGINE TEST');
    console.log('=' .repeat(60));
    console.log(`Running ${commands.length} commands\n`);

    const m = createZMachine();
    let outputBuffer = '';
    let allOutput = '';

    m.outputCallback = (text) => {
        outputBuffer += text;
        allOutput += text;
    };

    let cmdIndex = 0;

    // Progress tracking
    let lastProgressReport = 0;

    function showProgress() {
        if (cmdIndex - lastProgressReport >= 30) {
            console.log(`--- Progress: ${cmdIndex}/${commands.length} commands ---`);
            lastProgressReport = cmdIndex;
        }
    }

    return new Promise((resolve, reject) => {
        function feedNextCommand() {
            if (cmdIndex >= commands.length) {
                console.log('\n--- All commands executed ---\n');
                console.log('FINAL OUTPUT:');
                console.log(allOutput.slice(-2000));

                // Try to extract score
                const scoreMatch = allOutput.match(/(\d+)\s+(?:out of|\/)\s*(\d+)/i);
                if (scoreMatch) {
                    console.log(`\nFinal Score: ${scoreMatch[1]}/${scoreMatch[2]} points`);
                }

                // Check for victory
                if (allOutput.match(/\*\*\* You have won \*\*\*|You have won|Victory|Congratulations/i)) {
                    console.log('\n✓ VICTORY: Game completed!');
                }

                resolve({ success: true, output: allOutput });
                return;
            }

            showProgress();

            const cmd = commands[cmdIndex];
            cmdIndex++;

            if (m.inputCallback) {
                outputBuffer = '';
                m.inputCallback(cmd);
                setTimeout(feedNextCommand, 5);
            } else if (m.finished) {
                console.log('\n!!! Game finished early');
                console.log('Final output:');
                console.log(outputBuffer.slice(-500));
                resolve({ success: true, output: allOutput });
            } else {
                setTimeout(feedNextCommand, 10);
            }
        }

        process.on('uncaughtException', (err) => {
            console.error('\nError:', err.message);
            console.error('Command index:', cmdIndex);
            if (cmdIndex > 0) {
                console.error('Last command:', commands[cmdIndex - 1]);
            }
            reject(err);
        });

        try {
            m.run();
            setTimeout(feedNextCommand, 50);
        } catch (e) {
            console.error('Failed to start game:', e.message);
            reject(e);
        }
    });
}

test()
    .then((result) => {
        console.log('\n' + '=' .repeat(60));
        console.log(' TEST COMPLETE');
        console.log('=' .repeat(60));
        process.exit(0);
    })
    .catch((err) => {
        console.error('\nTest failed:', err);
        process.exit(1);
    });
