#!/usr/bin/env node
/**
 * Test planetfall with z2js
 *
 * Generated from solution JSON file
 * Commands: 600
 */

const { createZMachine } = require('./planetfall_z2js.js');

const commands = [
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "enter door",
    "go door",
    "enter",
    "in",
    "d",
    "down",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "enter door",
    "go door",
    "enter",
    "in",
    "d",
    "down",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "look",
    "examine port",
    "examine starboard",
    "examine entrance",
    "examine escape",
    "examine every",
    "examine leads",
    "examine away",
    "examine featureless",
    "examine closed",
    "examine similar",
    "take port",
    "take starboard",
    "take entrance",
    "take escape",
    "take every",
    "take leads",
    "take away",
    "take featureless",
    "take closed",
    "take similar",
    "open port",
    "open starboard",
    "open entrance",
    "open escape",
    "open every",
    "open leads",
    "open away",
    "open featureless",
    "open closed",
    "open similar",
    "read port",
    "read starboard",
    "read entrance",
    "read escape",
    "read every",
    "read leads",
    "read away",
    "read featureless",
    "read closed",
    "read similar",
    "move port",
    "move starboard",
    "move entrance",
    "move escape",
    "move every",
    "move leads",
    "move away",
    "move featureless",
    "move closed",
    "move similar",
    "push port",
    "push starboard",
    "push entrance",
    "push escape",
    "push every",
    "push leads",
    "push away",
    "push featureless",
    "push closed",
    "push similar",
    "pull port",
    "pull starboard",
    "pull entrance",
    "pull escape",
    "pull every",
    "pull leads",
    "pull away",
    "pull featureless",
    "pull closed",
    "pull similar",
    "turn port",
    "turn starboard",
    "turn entrance",
    "turn escape",
    "turn every",
    "turn leads",
    "turn away",
    "turn featureless",
    "turn closed",
    "turn similar",
    "light port",
    "light starboard",
    "light entrance",
    "light escape",
    "light every",
    "light leads",
    "light away",
    "light featureless",
    "light closed",
    "light similar",
    "look",
    "examine main",
    "examine area",
    "examine shade",
    "examine vessel",
    "examine standing",
    "examine continues",
    "examine onto",
    "examine drive",
    "take main",
    "take area",
    "take shade",
    "take vessel",
    "take standing",
    "take continues",
    "take onto",
    "take drive",
    "open main",
    "open area",
    "open shade",
    "open vessel",
    "open standing",
    "open continues",
    "open onto",
    "open drive",
    "read main",
    "read area",
    "read shade",
    "read vessel",
    "read standing",
    "read continues",
    "read onto",
    "read drive",
    "move main",
    "move area",
    "move shade",
    "move vessel",
    "move standing",
    "move continues",
    "move onto",
    "move drive",
    "push main",
    "push area",
    "push shade",
    "push vessel",
    "push standing",
    "push continues",
    "push onto",
    "push drive",
    "pull main",
    "pull area",
    "pull shade",
    "pull vessel",
    "pull standing",
    "pull continues",
    "pull onto",
    "pull drive",
    "turn main",
    "turn area",
    "turn shade",
    "turn vessel",
    "turn standing",
    "turn continues",
    "turn onto",
    "turn drive",
    "light main",
    "light area",
    "light shade",
    "light vessel",
    "light standing",
    "light continues",
    "light onto",
    "light drive",
    "look",
    "examine metal",
    "examine gangway",
    "examine steep",
    "examine below",
    "examine connecting",
    "examine above",
    "take metal",
    "take gangway",
    "take steep",
    "take below",
    "take connecting",
    "take above",
    "open metal",
    "open gangway",
    "open steep",
    "open below",
    "open connecting",
    "open above",
    "read metal",
    "read gangway",
    "read steep",
    "read below",
    "read connecting",
    "read above",
    "move metal",
    "move gangway",
    "move steep",
    "move below",
    "move connecting",
    "move above",
    "push metal",
    "push gangway",
    "push steep",
    "push below",
    "push connecting",
    "push above",
    "pull metal",
    "pull gangway",
    "pull steep",
    "pull below",
    "pull connecting",
    "pull above",
    "turn metal",
    "turn gangway",
    "turn steep",
    "turn below",
    "turn connecting",
    "turn above",
    "light metal",
    "light gangway",
    "light steep",
    "light below",
    "light connecting"
];

async function test() {
    console.log('=' .repeat(60));
    console.log(' PLANETFALL: Z2JS ENGINE TEST');
    console.log('=' .repeat(60));
    console.log(`Running ${commands.length} commands\n`);

    const m = createZMachine();
    let outputBuffer = '';
    let allOutput = '';

    m.outputCallback = (text) => {
        outputBuffer += text;
        allOutput += text;
    };

    let cmdIndex = 0;

    // Progress tracking
    let lastProgressReport = 0;

    function showProgress() {
        if (cmdIndex - lastProgressReport >= 30) {
            console.log(`--- Progress: ${cmdIndex}/${commands.length} commands ---`);
            lastProgressReport = cmdIndex;
        }
    }

    return new Promise((resolve, reject) => {
        function feedNextCommand() {
            if (cmdIndex >= commands.length) {
                console.log('\n--- All commands executed ---\n');
                console.log('FINAL OUTPUT:');
                console.log(allOutput.slice(-2000));

                // Try to extract score
                const scoreMatch = allOutput.match(/(\d+)\s+(?:out of|\/)\s*(\d+)/i);
                if (scoreMatch) {
                    console.log(`\nFinal Score: ${scoreMatch[1]}/${scoreMatch[2]} points`);
                }

                // Check for victory
                if (allOutput.match(/\*\*\* You have won \*\*\*|You have won|Victory|Congratulations/i)) {
                    console.log('\n✓ VICTORY: Game completed!');
                }

                resolve({ success: true, output: allOutput });
                return;
            }

            showProgress();

            const cmd = commands[cmdIndex];
            cmdIndex++;

            if (m.inputCallback) {
                outputBuffer = '';
                m.inputCallback(cmd);
                setTimeout(feedNextCommand, 5);
            } else if (m.finished) {
                console.log('\n!!! Game finished early');
                console.log('Final output:');
                console.log(outputBuffer.slice(-500));
                resolve({ success: true, output: allOutput });
            } else {
                setTimeout(feedNextCommand, 10);
            }
        }

        process.on('uncaughtException', (err) => {
            console.error('\nError:', err.message);
            console.error('Command index:', cmdIndex);
            if (cmdIndex > 0) {
                console.error('Last command:', commands[cmdIndex - 1]);
            }
            reject(err);
        });

        try {
            m.run();
            setTimeout(feedNextCommand, 50);
        } catch (e) {
            console.error('Failed to start game:', e.message);
            reject(e);
        }
    });
}

test()
    .then((result) => {
        console.log('\n' + '=' .repeat(60));
        console.log(' TEST COMPLETE');
        console.log('=' .repeat(60));
        process.exit(0);
    })
    .catch((err) => {
        console.error('\nTest failed:', err);
        process.exit(1);
    });
