#!/usr/bin/env node
/**
 * Test stationfall with z2js
 *
 * Generated from solution JSON file
 * Commands: 600
 */

const { createZMachine } = require('./stationfall_z2js.js');

const commands = [
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "enter window",
    "go window",
    "enter",
    "in",
    "d",
    "down",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "look",
    "examine heart",
    "examine ship",
    "examine port",
    "examine aft",
    "examine slot",
    "examine administrative",
    "examine continues",
    "examine other",
    "examine level",
    "examine that",
    "take heart",
    "take ship",
    "take port",
    "take aft",
    "take slot",
    "take administrative",
    "take continues",
    "take other",
    "take level",
    "take that",
    "open heart",
    "open ship",
    "open port",
    "open aft",
    "open slot",
    "open administrative",
    "open continues",
    "open other",
    "open level",
    "open that",
    "read heart",
    "read ship",
    "read port",
    "read aft",
    "read slot",
    "read administrative",
    "read continues",
    "read other",
    "read level",
    "read that",
    "move heart",
    "move ship",
    "move port",
    "move aft",
    "move slot",
    "move administrative",
    "move continues",
    "move other",
    "move level",
    "move that",
    "push heart",
    "push ship",
    "push port",
    "push aft",
    "push slot",
    "push administrative",
    "push continues",
    "push other",
    "push level",
    "push that",
    "pull heart",
    "pull ship",
    "pull port",
    "pull aft",
    "pull slot",
    "pull administrative",
    "pull continues",
    "pull other",
    "pull level",
    "pull that",
    "turn heart",
    "turn ship",
    "turn port",
    "turn aft",
    "turn slot",
    "turn administrative",
    "turn continues",
    "turn other",
    "turn level",
    "turn that",
    "light heart",
    "light ship",
    "light port",
    "light aft",
    "light slot",
    "light administrative",
    "light continues",
    "light other",
    "light level",
    "light that",
    "look",
    "examine decks",
    "examine filled",
    "examine upon",
    "examine area",
    "examine writing",
    "examine fore",
    "examine exit",
    "examine pallets",
    "examine room",
    "take decks",
    "take filled",
    "take upon",
    "take area",
    "take writing",
    "take fore",
    "take exit",
    "take pallets",
    "take room",
    "open decks",
    "open filled",
    "open upon",
    "open area",
    "open writing",
    "open fore",
    "open exit",
    "open pallets",
    "open room",
    "read decks",
    "read filled",
    "read upon",
    "read area",
    "read writing",
    "read fore",
    "read exit",
    "read pallets",
    "read room",
    "move decks",
    "move filled",
    "move upon",
    "move area",
    "move writing",
    "move fore",
    "move exit",
    "move pallets",
    "move room",
    "push decks",
    "push filled",
    "push upon",
    "push area",
    "push writing",
    "push fore",
    "push exit",
    "push pallets",
    "push room",
    "pull decks",
    "pull filled",
    "pull upon",
    "pull area",
    "pull writing",
    "pull fore",
    "pull exit",
    "pull pallets",
    "pull room",
    "turn decks",
    "turn filled",
    "turn upon",
    "turn area",
    "turn writing",
    "turn fore",
    "turn exit",
    "turn pallets",
    "turn room",
    "light decks",
    "light filled",
    "light upon",
    "light area",
    "light writing",
    "light fore",
    "light exit",
    "light pallets",
    "light room",
    "look",
    "examine smaller",
    "examine here",
    "examine cargo",
    "examine leads",
    "examine entrance",
    "examine bay",
    "examine starboard",
    "examine twelve",
    "examine ends",
    "take smaller",
    "take here",
    "take cargo",
    "take leads",
    "take entrance",
    "take bay",
    "take starboard",
    "take twelve",
    "take ends",
    "open smaller",
    "open here",
    "open cargo",
    "open leads",
    "open entrance",
    "open bay",
    "open starboard",
    "open twelve",
    "open ends",
    "read smaller",
    "read here",
    "read cargo",
    "read leads",
    "read entrance",
    "read bay",
    "read starboard",
    "read twelve",
    "read ends",
    "move smaller",
    "move here",
    "move cargo",
    "move leads",
    "move entrance",
    "move bay",
    "move starboard",
    "move twelve",
    "move ends",
    "push smaller",
    "push here",
    "push cargo",
    "push leads",
    "push entrance"
];

async function test() {
    console.log('=' .repeat(60));
    console.log(' STATIONFALL: Z2JS ENGINE TEST');
    console.log('=' .repeat(60));
    console.log(`Running ${commands.length} commands\n`);

    const m = createZMachine();
    let outputBuffer = '';
    let allOutput = '';

    m.outputCallback = (text) => {
        outputBuffer += text;
        allOutput += text;
    };

    let cmdIndex = 0;

    // Progress tracking
    let lastProgressReport = 0;

    function showProgress() {
        if (cmdIndex - lastProgressReport >= 30) {
            console.log(`--- Progress: ${cmdIndex}/${commands.length} commands ---`);
            lastProgressReport = cmdIndex;
        }
    }

    return new Promise((resolve, reject) => {
        function feedNextCommand() {
            if (cmdIndex >= commands.length) {
                console.log('\n--- All commands executed ---\n');
                console.log('FINAL OUTPUT:');
                console.log(allOutput.slice(-2000));

                // Try to extract score
                const scoreMatch = allOutput.match(/(\d+)\s+(?:out of|\/)\s*(\d+)/i);
                if (scoreMatch) {
                    console.log(`\nFinal Score: ${scoreMatch[1]}/${scoreMatch[2]} points`);
                }

                // Check for victory
                if (allOutput.match(/\*\*\* You have won \*\*\*|You have won|Victory|Congratulations/i)) {
                    console.log('\n✓ VICTORY: Game completed!');
                }

                resolve({ success: true, output: allOutput });
                return;
            }

            showProgress();

            const cmd = commands[cmdIndex];
            cmdIndex++;

            if (m.inputCallback) {
                outputBuffer = '';
                m.inputCallback(cmd);
                setTimeout(feedNextCommand, 5);
            } else if (m.finished) {
                console.log('\n!!! Game finished early');
                console.log('Final output:');
                console.log(outputBuffer.slice(-500));
                resolve({ success: true, output: allOutput });
            } else {
                setTimeout(feedNextCommand, 10);
            }
        }

        process.on('uncaughtException', (err) => {
            console.error('\nError:', err.message);
            console.error('Command index:', cmdIndex);
            if (cmdIndex > 0) {
                console.error('Last command:', commands[cmdIndex - 1]);
            }
            reject(err);
        });

        try {
            m.run();
            setTimeout(feedNextCommand, 50);
        } catch (e) {
            console.error('Failed to start game:', e.message);
            reject(e);
        }
    });
}

test()
    .then((result) => {
        console.log('\n' + '=' .repeat(60));
        console.log(' TEST COMPLETE');
        console.log('=' .repeat(60));
        process.exit(0);
    })
    .catch((err) => {
        console.error('\nTest failed:', err);
        process.exit(1);
    });
