#!/usr/bin/env node
/**
 * Test advent with z2js
 *
 * Generated from solution JSON file
 * Commands: 800
 */

const { createZMachine } = require('./advent_z2js.js');

const commands = [
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "north",
    "south",
    "east",
    "west",
    "up",
    "down",
    "enter",
    "exit",
    "enter switch",
    "enter road",
    "enter both",
    "enter door",
    "enter valley",
    "enter lamp",
    "enter trapdoor",
    "enter open",
    "enter bed",
    "enter instructions",
    "enter rocky",
    "enter knife",
    "enter bottle",
    "enter sword",
    "enter forest",
    "enter you",
    "enter adventure",
    "enter all",
    "enter stream",
    "enter ladder",
    "enter book",
    "enter window",
    "enter near",
    "enter gate",
    "enter deep",
    "enter chest",
    "enter grate",
    "enter tumbling",
    "enter beside",
    "enter side",
    "climb switch",
    "climb road",
    "climb both",
    "climb door",
    "climb valley",
    "climb lamp",
    "climb trapdoor",
    "climb open",
    "climb bed",
    "climb instructions",
    "climb rocky",
    "climb knife",
    "climb bottle",
    "climb sword",
    "climb forest",
    "climb you",
    "climb adventure",
    "climb all",
    "climb stream",
    "climb ladder",
    "climb book",
    "climb window",
    "climb near",
    "climb gate",
    "climb deep",
    "climb chest",
    "climb grate",
    "climb tumbling",
    "climb beside",
    "climb side",
    "open switch",
    "open road",
    "open both",
    "open door",
    "open valley",
    "open lamp",
    "open trapdoor",
    "open open",
    "open bed",
    "open instructions",
    "open rocky",
    "open knife",
    "open bottle",
    "open sword",
    "open forest",
    "open you",
    "open adventure",
    "open all",
    "open stream",
    "open ladder",
    "open book",
    "open window",
    "open near",
    "open gate",
    "open deep",
    "open chest",
    "open grate",
    "open tumbling",
    "open beside",
    "open side",
    "close switch",
    "close road",
    "close both",
    "close door",
    "close valley",
    "close lamp",
    "close trapdoor",
    "close open",
    "close bed",
    "close instructions",
    "close rocky",
    "close knife",
    "close bottle",
    "close sword",
    "close forest",
    "close you",
    "close adventure",
    "close all",
    "close stream",
    "close ladder",
    "close book",
    "close window",
    "close near",
    "close gate",
    "close deep",
    "close chest",
    "close grate",
    "close tumbling",
    "close beside",
    "close side",
    "unlock switch",
    "unlock road",
    "unlock both",
    "unlock door",
    "unlock valley",
    "unlock lamp",
    "unlock trapdoor",
    "unlock open",
    "unlock bed",
    "unlock instructions",
    "unlock rocky",
    "unlock knife",
    "unlock bottle",
    "unlock sword",
    "unlock forest",
    "unlock you",
    "unlock adventure",
    "unlock all",
    "unlock stream",
    "unlock ladder",
    "unlock book",
    "unlock window",
    "unlock near",
    "unlock gate",
    "unlock deep",
    "unlock chest",
    "unlock grate",
    "unlock tumbling",
    "unlock beside",
    "unlock side",
    "lock switch",
    "lock road",
    "lock both",
    "lock door",
    "lock valley",
    "lock lamp",
    "lock trapdoor",
    "lock open",
    "lock bed",
    "lock instructions",
    "lock rocky",
    "lock knife",
    "lock bottle",
    "lock sword",
    "lock forest",
    "lock you",
    "lock adventure",
    "lock all",
    "lock stream",
    "lock ladder",
    "lock book",
    "lock window",
    "lock near",
    "lock gate",
    "lock deep",
    "lock chest",
    "lock grate",
    "lock tumbling",
    "lock beside",
    "lock side",
    "take switch",
    "take road",
    "take both",
    "take door",
    "take valley",
    "take lamp",
    "take trapdoor",
    "take open",
    "take bed",
    "take instructions",
    "take rocky",
    "take knife",
    "take bottle",
    "take sword",
    "take forest",
    "take you",
    "take adventure",
    "take all",
    "take stream",
    "take ladder",
    "take book",
    "take window",
    "take near",
    "take gate",
    "take deep",
    "take chest",
    "take grate",
    "take tumbling",
    "take beside",
    "take side",
    "get switch",
    "get road",
    "get both",
    "get door",
    "get valley",
    "get lamp",
    "get trapdoor",
    "get open",
    "get bed",
    "get instructions",
    "get rocky",
    "get knife",
    "get bottle",
    "get sword",
    "get forest",
    "get you",
    "get adventure",
    "get all",
    "get stream",
    "get ladder",
    "get book",
    "get window",
    "get near",
    "get gate",
    "get deep",
    "get chest",
    "get grate",
    "get tumbling",
    "get beside",
    "get side",
    "drop switch",
    "drop road",
    "drop both",
    "drop door",
    "drop valley",
    "drop lamp",
    "drop trapdoor",
    "drop open",
    "drop bed",
    "drop instructions",
    "drop rocky",
    "drop knife",
    "drop bottle",
    "drop sword",
    "drop forest",
    "drop you",
    "drop adventure",
    "drop all",
    "drop stream",
    "drop ladder",
    "drop book",
    "drop window",
    "drop near",
    "drop gate",
    "drop deep",
    "drop chest",
    "drop grate",
    "drop tumbling",
    "drop beside",
    "drop side",
    "put switch",
    "put road",
    "put both",
    "put door",
    "put valley",
    "put lamp",
    "put trapdoor",
    "put open",
    "put bed",
    "put instructions",
    "put rocky",
    "put knife",
    "put bottle",
    "put sword",
    "put forest",
    "put you",
    "put adventure",
    "put all",
    "put stream",
    "put ladder",
    "put book",
    "put window",
    "put near",
    "put gate",
    "put deep",
    "put chest",
    "put grate",
    "put tumbling",
    "put beside",
    "put side",
    "push switch",
    "push road",
    "push both",
    "push door",
    "push valley",
    "push lamp",
    "push trapdoor",
    "push open",
    "push bed",
    "push instructions",
    "push rocky",
    "push knife",
    "push bottle",
    "push sword",
    "push forest",
    "push you",
    "push adventure",
    "push all",
    "push stream",
    "push ladder",
    "push book",
    "push window",
    "push near",
    "push gate",
    "push deep",
    "push chest",
    "push grate",
    "push tumbling",
    "push beside",
    "push side",
    "pull switch",
    "pull road",
    "pull both",
    "pull door",
    "pull valley",
    "pull lamp",
    "pull trapdoor",
    "pull open",
    "pull bed",
    "pull instructions",
    "pull rocky",
    "pull knife",
    "pull bottle",
    "pull sword",
    "pull forest",
    "pull you",
    "pull adventure",
    "pull all",
    "pull stream",
    "pull ladder",
    "pull book",
    "pull window",
    "pull near",
    "pull gate",
    "pull deep",
    "pull chest",
    "pull grate",
    "pull tumbling",
    "pull beside",
    "pull side",
    "turn switch",
    "turn road",
    "turn both",
    "turn door",
    "turn valley",
    "turn lamp",
    "turn trapdoor",
    "turn open",
    "turn bed",
    "turn instructions",
    "turn rocky",
    "turn knife",
    "turn bottle",
    "turn sword",
    "turn forest",
    "turn you",
    "turn adventure",
    "turn all",
    "turn stream",
    "turn ladder",
    "turn book",
    "turn window",
    "turn near",
    "turn gate",
    "turn deep",
    "turn chest",
    "turn grate",
    "turn tumbling",
    "turn beside",
    "turn side",
    "look switch",
    "look road",
    "look both",
    "look door",
    "look valley",
    "look lamp",
    "look trapdoor",
    "look open",
    "look bed",
    "look instructions",
    "look rocky",
    "look knife",
    "look bottle",
    "look sword",
    "look forest",
    "look you",
    "look adventure",
    "look all",
    "look stream",
    "look ladder",
    "look book",
    "look window",
    "look near",
    "look gate",
    "look deep",
    "look chest",
    "look grate",
    "look tumbling",
    "look beside",
    "look side",
    "read switch",
    "read road",
    "read both",
    "read door",
    "read valley",
    "read lamp",
    "read trapdoor",
    "read open",
    "read bed",
    "read instructions",
    "read rocky",
    "read knife",
    "read bottle",
    "read sword",
    "read forest",
    "read you",
    "read adventure",
    "read all",
    "read stream",
    "read ladder",
    "read book",
    "read window",
    "read near",
    "read gate",
    "read deep",
    "read chest",
    "read grate",
    "read tumbling",
    "read beside",
    "read side",
    "n",
    "east",
    "west",
    "up",
    "down",
    "enter",
    "exit",
    "enter switch",
    "enter distance",
    "enter door",
    "enter valley",
    "enter ground",
    "enter well",
    "enter knife",
    "enter bottle",
    "enter inside",
    "enter sword",
    "enter back",
    "enter still",
    "enter shiny",
    "enter forest",
    "enter you",
    "enter adventure",
    "enter stream",
    "enter standing",
    "enter ladder",
    "enter window",
    "enter near",
    "enter gate",
    "enter deep",
    "enter end",
    "enter slopes",
    "enter gully",
    "enter side",
    "enter sign",
    "enter before",
    "enter tasty food",
    "climb switch",
    "climb distance",
    "climb door",
    "climb valley",
    "climb ground",
    "climb well",
    "climb knife",
    "climb bottle",
    "climb inside",
    "climb sword",
    "climb back",
    "climb still",
    "climb shiny",
    "climb forest",
    "climb you",
    "climb adventure",
    "climb stream",
    "climb standing",
    "climb ladder",
    "climb window",
    "climb near",
    "climb gate",
    "climb deep",
    "climb end",
    "climb slopes",
    "climb gully",
    "climb side",
    "climb sign",
    "climb before",
    "climb tasty food",
    "open switch",
    "open distance",
    "open door",
    "open valley",
    "open ground",
    "open well",
    "open knife",
    "open bottle",
    "open inside",
    "open sword",
    "open back",
    "open still",
    "open shiny",
    "open forest",
    "open you",
    "open adventure",
    "open stream",
    "open standing",
    "open ladder",
    "open window",
    "open near",
    "open gate",
    "open deep",
    "open end",
    "open slopes",
    "open gully",
    "open side",
    "open sign",
    "open before",
    "open tasty food",
    "close switch",
    "close distance",
    "close door",
    "close valley",
    "close ground",
    "close well",
    "close knife",
    "close bottle",
    "close inside",
    "close sword",
    "close back",
    "close still",
    "close shiny",
    "close forest",
    "close you",
    "close adventure",
    "close stream",
    "close standing",
    "close ladder",
    "close window",
    "close near",
    "close gate",
    "close deep",
    "close end",
    "close slopes",
    "close gully",
    "close side",
    "close sign",
    "close before",
    "close tasty food",
    "unlock switch",
    "unlock distance",
    "unlock door",
    "unlock valley",
    "unlock ground",
    "unlock well",
    "unlock knife",
    "unlock bottle",
    "unlock inside",
    "unlock sword",
    "unlock back",
    "unlock still",
    "unlock shiny",
    "unlock forest",
    "unlock you",
    "unlock adventure",
    "unlock stream",
    "unlock standing",
    "unlock ladder",
    "unlock window",
    "unlock near",
    "unlock gate",
    "unlock deep",
    "unlock end",
    "unlock slopes",
    "unlock gully",
    "unlock side",
    "unlock sign",
    "unlock before",
    "unlock tasty food",
    "lock switch",
    "lock distance",
    "lock door",
    "lock valley",
    "lock ground",
    "lock well",
    "lock knife",
    "lock bottle",
    "lock inside",
    "lock sword",
    "lock back",
    "lock still",
    "lock shiny",
    "lock forest",
    "lock you",
    "lock adventure",
    "lock stream",
    "lock standing",
    "lock ladder",
    "lock window",
    "lock near",
    "lock gate",
    "lock deep",
    "lock end",
    "lock slopes",
    "lock gully",
    "lock side",
    "lock sign",
    "lock before",
    "lock tasty food",
    "take switch",
    "take distance",
    "take door",
    "take valley",
    "take ground",
    "take well",
    "take knife",
    "take bottle",
    "take inside",
    "take sword",
    "take back",
    "take still",
    "take shiny",
    "take forest",
    "take you",
    "take adventure",
    "take stream",
    "take standing",
    "take ladder",
    "take window",
    "take near",
    "take gate",
    "take deep",
    "take end",
    "take slopes",
    "take gully",
    "take side",
    "take sign",
    "take before",
    "take tasty food",
    "get switch",
    "get distance",
    "get door",
    "get valley",
    "get ground",
    "get well",
    "get knife",
    "get bottle",
    "get inside",
    "get sword",
    "get back",
    "get still",
    "get shiny",
    "get forest",
    "get you",
    "get adventure",
    "get stream",
    "get standing",
    "get ladder",
    "get window",
    "get near",
    "get gate",
    "get deep",
    "get end",
    "get slopes",
    "get gully",
    "get side",
    "get sign",
    "get before",
    "get tasty food",
    "drop switch",
    "drop distance",
    "drop door",
    "drop valley",
    "drop ground",
    "drop well",
    "drop knife",
    "drop bottle",
    "drop inside",
    "drop sword",
    "drop back",
    "drop still",
    "drop shiny",
    "drop forest",
    "drop you",
    "drop adventure",
    "drop stream",
    "drop standing",
    "drop ladder",
    "drop window",
    "drop near",
    "drop gate",
    "drop deep",
    "drop end",
    "drop slopes",
    "drop gully",
    "drop side",
    "drop sign",
    "drop before",
    "drop tasty food",
    "put switch",
    "put distance",
    "put door",
    "put valley",
    "put ground",
    "put well",
    "put knife",
    "put bottle",
    "put inside",
    "put sword",
    "put back",
    "put still",
    "put shiny",
    "put forest",
    "put you",
    "put adventure",
    "put stream",
    "put standing",
    "put ladder",
    "put window",
    "put near",
    "put gate",
    "put deep",
    "put end",
    "put slopes",
    "put gully",
    "put side",
    "put sign",
    "put before",
    "put tasty food",
    "push switch",
    "push distance",
    "push door",
    "push valley",
    "push ground",
    "push well",
    "push knife"
];

async function test() {
    console.log('=' .repeat(60));
    console.log(' ADVENT: Z2JS ENGINE TEST');
    console.log('=' .repeat(60));
    console.log(`Running ${commands.length} commands\n`);

    const m = createZMachine();
    let outputBuffer = '';
    let allOutput = '';

    m.outputCallback = (text) => {
        outputBuffer += text;
        allOutput += text;
    };

    let cmdIndex = 0;

    // Progress tracking
    let lastProgressReport = 0;

    function showProgress() {
        if (cmdIndex - lastProgressReport >= 30) {
            console.log(`--- Progress: ${cmdIndex}/${commands.length} commands ---`);
            lastProgressReport = cmdIndex;
        }
    }

    return new Promise((resolve, reject) => {
        function feedNextCommand() {
            if (cmdIndex >= commands.length) {
                console.log('\n--- All commands executed ---\n');
                console.log('FINAL OUTPUT:');
                console.log(allOutput.slice(-2000));

                // Try to extract score
                const scoreMatch = allOutput.match(/(\d+)\s+(?:out of|\/)\s*(\d+)/i);
                if (scoreMatch) {
                    console.log(`\nFinal Score: ${scoreMatch[1]}/${scoreMatch[2]} points`);
                }

                // Check for victory
                if (allOutput.match(/\*\*\* You have won \*\*\*|You have won|Victory|Congratulations/i)) {
                    console.log('\n✓ VICTORY: Game completed!');
                }

                resolve({ success: true, output: allOutput });
                return;
            }

            showProgress();

            const cmd = commands[cmdIndex];
            cmdIndex++;

            if (m.inputCallback) {
                outputBuffer = '';
                m.inputCallback(cmd);
                setTimeout(feedNextCommand, 5);
            } else if (m.finished) {
                console.log('\n!!! Game finished early');
                console.log('Final output:');
                console.log(outputBuffer.slice(-500));
                resolve({ success: true, output: allOutput });
            } else {
                setTimeout(feedNextCommand, 10);
            }
        }

        process.on('uncaughtException', (err) => {
            console.error('\nError:', err.message);
            console.error('Command index:', cmdIndex);
            if (cmdIndex > 0) {
                console.error('Last command:', commands[cmdIndex - 1]);
            }
            reject(err);
        });

        try {
            m.run();
            setTimeout(feedNextCommand, 50);
        } catch (e) {
            console.error('Failed to start game:', e.message);
            reject(e);
        }
    });
}

test()
    .then((result) => {
        console.log('\n' + '=' .repeat(60));
        console.log(' TEST COMPLETE');
        console.log('=' .repeat(60));
        process.exit(0);
    })
    .catch((err) => {
        console.error('\nTest failed:', err);
        process.exit(1);
    });
