#!/usr/bin/env node
/**
 * Test pentari with z2js
 *
 * Generated from solution JSON file
 * Commands: 500
 */

const { createZMachine } = require('./pentari_z2js.js');

const commands = [
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "enter chest",
    "go chest",
    "enter",
    "in",
    "d",
    "down",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter box",
    "go box",
    "enter",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take knife",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take leaflet",
    "take egg",
    "take jewels",
    "take coins",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter box",
    "go box",
    "enter",
    "in",
    "d",
    "down",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "enter chest",
    "go chest",
    "enter",
    "in",
    "d",
    "down",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "open window",
    "open door",
    "open gate",
    "open trapdoor",
    "move rug",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "enter",
    "climb down",
    "climb up",
    "open trap door",
    "unlock door",
    "unlock gate",
    "look",
    "examine previous",
    "examine certainly",
    "examine power",
    "examine have",
    "examine abuse",
    "examine company",
    "examine quarters",
    "examine bunk",
    "examine does",
    "examine supply",
    "take previous",
    "take certainly",
    "take power",
    "take have",
    "take abuse",
    "take company",
    "take quarters",
    "take bunk",
    "take does",
    "take supply",
    "open previous",
    "open certainly",
    "open power",
    "open have",
    "open abuse",
    "open company",
    "open quarters",
    "open bunk",
    "open does",
    "open supply",
    "read previous",
    "read certainly",
    "read power",
    "read have",
    "read abuse",
    "read company",
    "read quarters",
    "read bunk",
    "read does",
    "read supply",
    "move previous",
    "move certainly",
    "move power",
    "move have",
    "move abuse",
    "move company",
    "move quarters",
    "move bunk",
    "move does",
    "move supply",
    "push previous",
    "push certainly",
    "push power",
    "push have",
    "push abuse",
    "push company",
    "push quarters",
    "push bunk",
    "push does",
    "push supply",
    "pull previous",
    "pull certainly",
    "pull power",
    "pull have",
    "pull abuse",
    "pull company",
    "pull quarters",
    "pull bunk",
    "pull does",
    "pull supply",
    "turn previous",
    "turn certainly",
    "turn power",
    "turn have",
    "turn abuse",
    "turn company",
    "turn quarters",
    "turn bunk",
    "turn does",
    "turn supply",
    "light previous",
    "light certainly",
    "light power",
    "light have",
    "light abuse",
    "light company",
    "light quarters",
    "light bunk",
    "light does",
    "light supply",
    "look",
    "examine quieter",
    "examine distant",
    "examine directly",
    "examine area",
    "examine buildings",
    "examine lies",
    "examine another",
    "examine than",
    "examine shouts",
    "take quieter",
    "take distant",
    "take directly",
    "take area",
    "take buildings",
    "take lies",
    "take another",
    "take than",
    "take shouts",
    "open quieter",
    "open distant",
    "open directly",
    "open area",
    "open buildings",
    "open lies",
    "open another",
    "open than",
    "open shouts",
    "read quieter",
    "read distant",
    "read directly",
    "read area",
    "read buildings",
    "read lies",
    "read another",
    "read than",
    "read shouts",
    "move quieter",
    "move distant",
    "move directly",
    "move area",
    "move buildings",
    "move lies",
    "move another",
    "move than",
    "move shouts",
    "push quieter",
    "push distant",
    "push directly",
    "push area",
    "push buildings",
    "push lies",
    "push another",
    "push than",
    "push shouts",
    "pull quieter",
    "pull distant",
    "pull directly",
    "pull area",
    "pull buildings",
    "pull lies",
    "pull another",
    "pull than",
    "pull shouts",
    "turn quieter",
    "turn distant",
    "turn directly",
    "turn area",
    "turn buildings",
    "turn lies",
    "turn another",
    "turn than",
    "turn shouts",
    "light quieter",
    "light distant",
    "light directly",
    "light area",
    "light buildings",
    "light lies",
    "light another",
    "light than",
    "light shouts",
    "look",
    "examine powerful",
    "examine article",
    "examine nearly",
    "examine nostrils",
    "examine comapny",
    "examine edition",
    "examine shine",
    "examine floors",
    "examine this"
];

async function test() {
    console.log('=' .repeat(60));
    console.log(' PENTARI: Z2JS ENGINE TEST');
    console.log('=' .repeat(60));
    console.log(`Running ${commands.length} commands\n`);

    const m = createZMachine();
    let outputBuffer = '';
    let allOutput = '';

    m.outputCallback = (text) => {
        outputBuffer += text;
        allOutput += text;
    };

    let cmdIndex = 0;

    // Progress tracking
    let lastProgressReport = 0;

    function showProgress() {
        if (cmdIndex - lastProgressReport >= 30) {
            console.log(`--- Progress: ${cmdIndex}/${commands.length} commands ---`);
            lastProgressReport = cmdIndex;
        }
    }

    return new Promise((resolve, reject) => {
        function feedNextCommand() {
            if (cmdIndex >= commands.length) {
                console.log('\n--- All commands executed ---\n');
                console.log('FINAL OUTPUT:');
                console.log(allOutput.slice(-2000));

                // Try to extract score
                const scoreMatch = allOutput.match(/(\d+)\s+(?:out of|\/)\s*(\d+)/i);
                if (scoreMatch) {
                    console.log(`\nFinal Score: ${scoreMatch[1]}/${scoreMatch[2]} points`);
                }

                // Check for victory
                if (allOutput.match(/\*\*\* You have won \*\*\*|You have won|Victory|Congratulations/i)) {
                    console.log('\n✓ VICTORY: Game completed!');
                }

                resolve({ success: true, output: allOutput });
                return;
            }

            showProgress();

            const cmd = commands[cmdIndex];
            cmdIndex++;

            if (m.inputCallback) {
                outputBuffer = '';
                m.inputCallback(cmd);
                setTimeout(feedNextCommand, 5);
            } else if (m.finished) {
                console.log('\n!!! Game finished early');
                console.log('Final output:');
                console.log(outputBuffer.slice(-500));
                resolve({ success: true, output: allOutput });
            } else {
                setTimeout(feedNextCommand, 10);
            }
        }

        process.on('uncaughtException', (err) => {
            console.error('\nError:', err.message);
            console.error('Command index:', cmdIndex);
            if (cmdIndex > 0) {
                console.error('Last command:', commands[cmdIndex - 1]);
            }
            reject(err);
        });

        try {
            m.run();
            setTimeout(feedNextCommand, 50);
        } catch (e) {
            console.error('Failed to start game:', e.message);
            reject(e);
        }
    });
}

test()
    .then((result) => {
        console.log('\n' + '=' .repeat(60));
        console.log(' TEST COMPLETE');
        console.log('=' .repeat(60));
        process.exit(0);
    })
    .catch((err) => {
        console.error('\nTest failed:', err);
        process.exit(1);
    });
