#!/usr/bin/env node
/**
 * Smart test for acheton with z2js
 *
 * Handles random events (combat, thief, grue, etc.)
 * Commands: 2444
 */

const { createZMachine } = require('./acheton_z2js.js');

// Suppress z2js noise ("[Z-Machine execution stopped]")
const originalError = console.error;
console.error = (...args) => {
    const msg = args.join(' ');
    if (!msg.includes('Z-Machine execution stopped')) {
        originalError.apply(console, args);
    }
};

const commands = [
    "examine",
    "take amulet",
    "north",
    "examine door",
    "open door",
    "take amulet",
    "north",
    "examine door",
    "open door",
    "take amulet",
    "examine amulet",
    "north",
    "examine door",
    "open door",
    "take amulet",
    "examine amulet",
    "north",
    "examine door",
    "open door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "open door",
    "north",
    "examine amulet",
    "take amulet",
    "north",
    "examine door",
    "open door",
    "take amulet",
    "open door",
    "north",
    "examine altar",
    "examine statue",
    "take amulet",
    "examine altar",
    "answer question",
    "north",
    "examine statue",
    "take amulet",
    "examine altar",
    "answer question",
    "north",
    "examine statue",
    "take amulet",
    "answer question",
    "north",
    "examine statue",
    "examine altar",
    "take amulet",
    "answer question",
    "examine statue",
    "examine altar",
    "take amulet",
    "answer question",
    "examine statue",
    "examine altar",
    "take amulet",
    "examine amulet",
    "examine statue",
    "answer question",
    "take amulet",
    "examine amulet",
    "answer question",
    "examine statue",
    "go north",
    "take amulet",
    "answer question",
    "go north",
    "examine statue",
    "examine altar",
    "answer question y",
    "take amulet",
    "go north",
    "examine statue",
    "examine altar",
    "examine statue",
    "take amulet",
    "go north",
    "examine altar",
    "say abracadabra",
    "take amulet",
    "examine altar",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "examine altar",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "examine room",
    "take amulet",
    "examine statue",
    "say abracadabra",
    "go north",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "examine room",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "examine room",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "examine room",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "examine room",
    "examine statue",
    "say abracadabra",
    "take amulet",
    "go north",
    "go east",
    "examine statue",
    "say abracadabra",
    "take amulet",
    "go north",
    "go east",
    "take amulet",
    "go east",
    "examine amulet",
    "drop amulet",
    "go west",
    "take amulet",
    "examine amulet",
    "go east",
    "go west",
    "take amulet",
    "examine amulet",
    "go east",
    "go west",
    "go west",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "go up",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "go up",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "go up",
    "take amulet",
    "go east",
    "go north",
    "take amber",
    "examine amber",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amber",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amber",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amber",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amber",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amber",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "take amber",
    "go north",
    "go east",
    "examine altar",
    "take amulet",
    "take amber",
    "go north",
    "examine altar",
    "take amulet",
    "take amber",
    "go north",
    "examine altar",
    "take amulet",
    "take amber",
    "go north",
    "examine altar",
    "say abracadabra",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine altar",
    "take amber",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine altar",
    "take amber",
    "take amulet",
    "take amber",
    "examine altar",
    "go north",
    "take amulet",
    "go north",
    "examine altar",
    "take amber",
    "abracadab",
    "take amulet",
    "examine altar",
    "take amber",
    "abracadab",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "abracadab",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "abracadab",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "abracadab",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "abracadab",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "abracadab",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "take amber",
    "go north",
    "examine anaconda",
    "unlock door",
    "take amulet",
    "take amber",
    "go north",
    "unlock door",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "examine anaconda",
    "take amber",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "go north",
    "unlock door",
    "take amber",
    "examine anaconda",
    "take amulet",
    "go north",
    "examine anaconda",
    "take amber",
    "take adamant",
    "take amulet",
    "go north",
    "take amber",
    "take adamant",
    "examine anaconda",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "examine altar",
    "take adamant",
    "examine anaconda",
    "go north",
    "examine altar",
    "take amulet",
    "take amulet",
    "examine amulet",
    "go north",
    "examine altar",
    "take adamant",
    "take amulet",
    "examine amulet",
    "go north",
    "take adamant",
    "examine altar",
    "take amulet",
    "examine amulet",
    "go north",
    "take adamant",
    "examine altar",
    "take amulet",
    "examine amulet",
    "go north",
    "take adamant",
    "examine altar",
    "take amulet",
    "examine amulet",
    "go north",
    "take adamant",
    "examine altar",
    "take amulet",
    "examine amulet",
    "go north",
    "take adamant",
    "examine altar",
    "take amulet",
    "examine amulet",
    "go north",
    "take adamant",
    "examine altar",
    "take amulet",
    "go north",
    "take adamant",
    "examine altar",
    "say abra",
    "take amulet",
    "say abra",
    "examine altar",
    "go north",
    "take adamant",
    "take amulet",
    "examine altar",
    "go north",
    "take adamant",
    "take amulet",
    "examine altar",
    "go north",
    "take adamant",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "go north",
    "take adamant",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "examine altar",
    "take adamant",
    "go north",
    "examine anaconda",
    "take amulet",
    "take adamant",
    "examine altar",
    "go north",
    "examine anaconda",
    "take amulet",
    "take adamant",
    "examine altar",
    "go north",
    "examine anaconda",
    "examine altar",
    "take adamant",
    "go north",
    "examine anaconda",
    "take amulet",
    "take adamant",
    "take amulet",
    "go north",
    "examine anaconda",
    "examine altar",
    "take amulet",
    "examine amulet",
    "go north",
    "examine altar",
    "pray",
    "take amulet",
    "pray",
    "go north",
    "examine altar",
    "examine amulet",
    "take amulet",
    "pray",
    "go north",
    "examine altar",
    "examine amulet",
    "examine altar",
    "take amulet",
    "pray",
    "go north",
    "examine amulet",
    "take amulet",
    "examine amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "examine altar",
    "pray",
    "take amulet",
    "wear amulet",
    "go north",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "go north",
    "take amulet",
    "wear amulet",
    "go north",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take offerings",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take offerings",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take offerings",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take offerings",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "take offerings",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take offerings",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take offerings",
    "wear amulet",
    "go north",
    "examine altar",
    "examine amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take offerings",
    "wear amulet",
    "examine altar",
    "go north",
    "examine cave",
    "examine altar",
    "take offerings",
    "wear amulet",
    "go north",
    "examine cave",
    "take offerings",
    "wear amulet",
    "go north",
    "examine cave",
    "examine altar",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take offerings",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take offerings",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "take offerings",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "go north",
    "examine altar",
    "pray",
    "take offerings",
    "wear amulet",
    "go north",
    "examine altar",
    "pray",
    "take offerings",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine amulet",
    "examine amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "wear amulet",
    "pray",
    "examine altar",
    "go north",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take agate",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine amulet",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine amulet",
    "examine altar",
    "examine altar",
    "pray",
    "wear amulet",
    "go north",
    "examine amulet",
    "pray",
    "wear amulet",
    "go north",
    "examine amulet",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "pray",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "examine altar",
    "go north",
    "pray",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "look",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "look",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take adamant",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar"
];

// Random event patterns to detect
const randomEvents = [
    { id: "thief_encounter", name: "Thief", pattern: /thief|someone carrying a large bag|nasty knife|stiletto/i, checkItem: "sword" },
    { id: "troll_encounter", name: "Troll", pattern: /troll|nasty troll|dangerous troll/i, checkItem: "sword" },
    { id: "grue_warning", name: "Grue", pattern: /eaten by a grue|lurking grue|grue is|pitch black|dark\\..*eaten/i, checkItem: "lamp" },
    { id: "combat_attack", name: "Combat", pattern: /attacks you|strikes at you|swings at you|lunges at you|hits you/i, checkItem: "sword" },
    { id: "cyclops_encounter", name: "Cyclops", pattern: /cyclops|one-eyed giant/i, checkItem: null }
];

// Responses for each event type
const eventResponses = {
    "thief_encounter": {"has_sword": ["kill thief with sword", "attack thief with sword"], "default": ["drop all", "wait", "wait", "wait", "take all"]},
    "troll_encounter": {"has_sword": ["kill troll with sword", "attack troll"], "default": ["flee", "run", "retreat"]},
    "grue_warning": {"has_lamp": ["turn on lamp", "light lamp"], "default": ["go back", "retreat", "flee"]},
    "combat_attack": {"has_sword": ["kill attacker with sword", "attack", "fight"], "default": ["flee", "run"]},
    "cyclops_encounter": {"default": ["give lunch to cyclops", "say odysseus", "odysseus", "ulysses"]}
};

async function test() {
    console.log('='.repeat(60));
    console.log(' ACHETON: SMART Z2JS TEST');
    console.log('='.repeat(60));
    console.log(`Running ${commands.length} commands (with random event handling)\n`);

    const m = createZMachine();
    let outputBuffer = '';
    let allOutput = '';
    let inventory = new Set();  // Track inventory for conditional responses

    m.outputCallback = (text) => {
        outputBuffer += text;
        allOutput += text;

        // Track inventory changes
        if (/you.*(?:take|get|pick up)/i.test(text)) {
            const itemMatch = text.match(/(?:take|get|pick up)\s+(?:the\s+)?([\w\s]+)/i);
            if (itemMatch) inventory.add(itemMatch[1].toLowerCase().trim());
        }
        if (/taken/i.test(text) && outputBuffer.length < 50) {
            // Short "Taken." response - item from last command
        }
    };

    let cmdIndex = 0;
    let eventCommandsQueue = [];  // Commands to handle current event
    let handlingEvent = false;
    let eventsHandled = 0;
    let lastProgressReport = 0;

    function checkForRandomEvent(output) {
        for (const event of randomEvents) {
            if (event.pattern.test(output)) {
                return event;
            }
        }
        return null;
    }

    function getEventResponse(event) {
        const responses = eventResponses[event.id];
        if (!responses) return [];

        // Check if we have the required item for special response
        if (event.checkItem && inventory.has(event.checkItem)) {
            const key = `has_${event.checkItem}`;
            if (responses[key]) return [...responses[key]];
        }

        return responses.default ? [...responses.default] : [];
    }

    function showProgress() {
        if (cmdIndex - lastProgressReport >= 30) {
            console.log(`--- Progress: ${cmdIndex}/${commands.length} commands (events handled: ${eventsHandled}) ---`);
            lastProgressReport = cmdIndex;
        }
    }

    return new Promise((resolve, reject) => {
        function feedNextCommand() {
            // First, check if we detected a random event in last output
            if (!handlingEvent) {
                const event = checkForRandomEvent(outputBuffer);
                if (event) {
                    console.log(`\n>>> RANDOM EVENT: ${event.name} detected!`);
                    eventCommandsQueue = getEventResponse(event);
                    if (eventCommandsQueue.length > 0) {
                        handlingEvent = true;
                        eventsHandled++;
                        console.log(`    Responding with: ${eventCommandsQueue[0]}`);
                    }
                }
            }

            // Handle event commands first
            if (handlingEvent && eventCommandsQueue.length > 0) {
                const eventCmd = eventCommandsQueue.shift();
                if (eventCommandsQueue.length === 0) {
                    handlingEvent = false;  // Done with this event
                }

                if (m.inputCallback) {
                    outputBuffer = '';
                    m.inputCallback(eventCmd);
                    setTimeout(feedNextCommand, 5);
                    return;
                }
            }

            // Normal command processing
            if (cmdIndex >= commands.length) {
                console.log('\n--- All commands executed ---');
                console.log(`Events handled: ${eventsHandled}\n`);
                console.log('FINAL OUTPUT (last 1500 chars):');
                console.log(allOutput.slice(-1500));

                // Extract score
                const scoreMatch = allOutput.match(/(\d+)\s*(?:out of|\/)\s*(\d+)/i);
                if (scoreMatch) {
                    console.log(`\nFinal Score: ${scoreMatch[1]}/${scoreMatch[2]} points`);
                }

                // Check victory
                if (/\*\*\* You have won \*\*\*|You have won|Victory|Congratulations/i.test(allOutput)) {
                    console.log('\n✓ VICTORY: Game completed!');
                }

                resolve({ success: true, output: allOutput, eventsHandled });
                return;
            }

            showProgress();

            const cmd = commands[cmdIndex];
            cmdIndex++;

            // Track take commands for inventory
            if (/^(?:take|get|pick up)\s+/i.test(cmd)) {
                const itemMatch = cmd.match(/^(?:take|get|pick up)\s+(?:the\s+)?(.+)/i);
                if (itemMatch) inventory.add(itemMatch[1].toLowerCase().trim());
            }

            if (m.inputCallback) {
                outputBuffer = '';
                m.inputCallback(cmd);
                setTimeout(feedNextCommand, 5);
            } else if (m.finished) {
                console.log('\n!!! Game finished early');
                console.log('Final output:', outputBuffer.slice(-500));
                resolve({ success: true, output: allOutput, eventsHandled });
            } else {
                setTimeout(feedNextCommand, 10);
            }
        }

        process.on('uncaughtException', (err) => {
            console.error('\nError:', err.message);
            console.error('Command index:', cmdIndex);
            if (cmdIndex > 0) console.error('Last command:', commands[cmdIndex - 1]);
            reject(err);
        });

        try {
            m.run();
            setTimeout(feedNextCommand, 50);
        } catch (e) {
            console.error('Failed to start:', e.message);
            reject(e);
        }
    });
}

test()
    .then((result) => {
        console.log('\n' + '='.repeat(60));
        console.log(` TEST COMPLETE - Events: ${result.eventsHandled}`);
        console.log('='.repeat(60));
        process.exit(0);
    })
    .catch((err) => {
        console.error('\nTest failed:', err);
        process.exit(1);
    });
