#!/usr/bin/env node
/**
 * Test zork1 with z2js
 *
 * Generated from solution JSON file
 * Commands: 800
 */

const { createZMachine } = require('./zork1_z2js.js');

const commands = [
    "n",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "s",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "e",
    "w",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "n",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "s",
    "e",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "w",
    "open window",
    "open door",
    "enter",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "w",
    "u",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "u",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "in",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "open window",
    "open door",
    "enter",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "n",
    "north",
    "south",
    "east",
    "west",
    "exit",
    "enter heads",
    "enter behind",
    "enter door",
    "enter nailed",
    "enter northwest",
    "enter likely",
    "enter extends",
    "enter side",
    "enter died",
    "enter elvish",
    "enter falls",
    "enter winds",
    "enter directions",
    "enter corner",
    "enter gold",
    "enter doorway",
    "enter case",
    "enter moved",
    "enter brass",
    "enter trademark",
    "enter oriental",
    "enter slavering",
    "enter elongated",
    "enter switch",
    "enter grue",
    "enter room",
    "enter edge",
    "enter thins",
    "enter all",
    "enter marvelous",
    "exit heads",
    "exit behind",
    "exit door",
    "exit nailed",
    "exit northwest",
    "exit likely",
    "exit extends",
    "exit side",
    "exit died",
    "exit elvish",
    "exit falls",
    "exit winds",
    "exit directions",
    "exit corner",
    "exit gold",
    "exit doorway",
    "exit case",
    "exit moved",
    "exit brass",
    "exit trademark",
    "exit oriental",
    "exit slavering",
    "exit elongated",
    "exit switch",
    "exit grue",
    "exit room",
    "exit edge",
    "exit thins",
    "exit all",
    "exit marvelous",
    "climb heads",
    "climb behind",
    "climb door",
    "climb nailed",
    "climb northwest",
    "climb likely",
    "climb extends",
    "climb side",
    "climb died",
    "climb elvish",
    "climb falls",
    "climb winds",
    "climb directions",
    "climb corner",
    "climb gold",
    "climb doorway",
    "climb case",
    "climb moved",
    "climb brass",
    "climb trademark",
    "climb oriental",
    "climb slavering",
    "climb elongated",
    "climb switch",
    "climb grue",
    "climb room",
    "climb edge",
    "climb thins",
    "climb all",
    "climb marvelous",
    "open heads",
    "open behind",
    "open nailed",
    "open northwest",
    "open likely",
    "open extends",
    "open side",
    "open died",
    "open elvish",
    "open falls",
    "open winds",
    "open directions",
    "open corner",
    "open gold",
    "open doorway",
    "open case",
    "open moved",
    "open brass",
    "open trademark",
    "open oriental",
    "open slavering",
    "open elongated",
    "open switch",
    "open grue",
    "open room",
    "open edge",
    "open thins",
    "open all",
    "open marvelous",
    "close heads",
    "close behind",
    "close door",
    "close nailed",
    "close northwest",
    "close likely",
    "close extends",
    "close side",
    "close died",
    "close elvish",
    "close falls",
    "close winds",
    "close directions",
    "close corner",
    "close gold",
    "close doorway",
    "close case"
];

async function test() {
    console.log('=' .repeat(60));
    console.log(' ZORK1: Z2JS ENGINE TEST');
    console.log('=' .repeat(60));
    console.log(`Running ${commands.length} commands\n`);

    const m = createZMachine();
    let outputBuffer = '';
    let allOutput = '';

    m.outputCallback = (text) => {
        outputBuffer += text;
        allOutput += text;
    };

    let cmdIndex = 0;

    // Progress tracking
    let lastProgressReport = 0;

    function showProgress() {
        if (cmdIndex - lastProgressReport >= 30) {
            console.log(`--- Progress: ${cmdIndex}/${commands.length} commands ---`);
            lastProgressReport = cmdIndex;
        }
    }

    return new Promise((resolve, reject) => {
        function feedNextCommand() {
            if (cmdIndex >= commands.length) {
                console.log('\n--- All commands executed ---\n');
                console.log('FINAL OUTPUT:');
                console.log(allOutput.slice(-2000));

                // Try to extract score
                const scoreMatch = allOutput.match(/(\d+)\s+(?:out of|\/)\s*(\d+)/i);
                if (scoreMatch) {
                    console.log(`\nFinal Score: ${scoreMatch[1]}/${scoreMatch[2]} points`);
                }

                // Check for victory
                if (allOutput.match(/\*\*\* You have won \*\*\*|You have won|Victory|Congratulations/i)) {
                    console.log('\n✓ VICTORY: Game completed!');
                }

                resolve({ success: true, output: allOutput });
                return;
            }

            showProgress();

            const cmd = commands[cmdIndex];
            cmdIndex++;

            if (m.inputCallback) {
                outputBuffer = '';
                m.inputCallback(cmd);
                setTimeout(feedNextCommand, 5);
            } else if (m.finished) {
                console.log('\n!!! Game finished early');
                console.log('Final output:');
                console.log(outputBuffer.slice(-500));
                resolve({ success: true, output: allOutput });
            } else {
                setTimeout(feedNextCommand, 10);
            }
        }

        process.on('uncaughtException', (err) => {
            console.error('\nError:', err.message);
            console.error('Command index:', cmdIndex);
            if (cmdIndex > 0) {
                console.error('Last command:', commands[cmdIndex - 1]);
            }
            reject(err);
        });

        try {
            m.run();
            setTimeout(feedNextCommand, 50);
        } catch (e) {
            console.error('Failed to start game:', e.message);
            reject(e);
        }
    });
}

test()
    .then((result) => {
        console.log('\n' + '=' .repeat(60));
        console.log(' TEST COMPLETE');
        console.log('=' .repeat(60));
        process.exit(0);
    })
    .catch((err) => {
        console.error('\nTest failed:', err);
        process.exit(1);
    });
