#!/usr/bin/env node
/**
 * Test acheton with z2js
 *
 * Generated from solution JSON file
 * Commands: 2444
 */

const { createZMachine } = require('./acheton_z2js.js');

const commands = [
    "examine",
    "take amulet",
    "north",
    "examine door",
    "open door",
    "take amulet",
    "north",
    "examine door",
    "open door",
    "take amulet",
    "examine amulet",
    "north",
    "examine door",
    "open door",
    "take amulet",
    "examine amulet",
    "north",
    "examine door",
    "open door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "north",
    "open door",
    "examine door",
    "take amulet",
    "examine amulet",
    "open door",
    "north",
    "examine amulet",
    "take amulet",
    "north",
    "examine door",
    "open door",
    "take amulet",
    "open door",
    "north",
    "examine altar",
    "examine statue",
    "take amulet",
    "examine altar",
    "answer question",
    "north",
    "examine statue",
    "take amulet",
    "examine altar",
    "answer question",
    "north",
    "examine statue",
    "take amulet",
    "answer question",
    "north",
    "examine statue",
    "examine altar",
    "take amulet",
    "answer question",
    "examine statue",
    "examine altar",
    "take amulet",
    "answer question",
    "examine statue",
    "examine altar",
    "take amulet",
    "examine amulet",
    "examine statue",
    "answer question",
    "take amulet",
    "examine amulet",
    "answer question",
    "examine statue",
    "go north",
    "take amulet",
    "answer question",
    "go north",
    "examine statue",
    "examine altar",
    "answer question y",
    "take amulet",
    "go north",
    "examine statue",
    "examine altar",
    "examine statue",
    "take amulet",
    "go north",
    "examine altar",
    "say abracadabra",
    "take amulet",
    "examine altar",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "examine altar",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "examine room",
    "take amulet",
    "examine statue",
    "say abracadabra",
    "go north",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "examine room",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "examine room",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "examine room",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine statue",
    "examine room",
    "examine statue",
    "say abracadabra",
    "take amulet",
    "go north",
    "go east",
    "examine statue",
    "say abracadabra",
    "take amulet",
    "go north",
    "go east",
    "take amulet",
    "go east",
    "examine amulet",
    "drop amulet",
    "go west",
    "take amulet",
    "examine amulet",
    "go east",
    "go west",
    "take amulet",
    "examine amulet",
    "go east",
    "go west",
    "go west",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "go up",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "go up",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "go up",
    "take amulet",
    "go east",
    "go north",
    "take amber",
    "examine amber",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amber",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amber",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amber",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amber",
    "take amulet",
    "examine amulet",
    "go east",
    "go north",
    "take amber",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "examine amulet",
    "go east",
    "take amber",
    "go north",
    "take amulet",
    "take amber",
    "go north",
    "go east",
    "examine altar",
    "take amulet",
    "take amber",
    "go north",
    "examine altar",
    "take amulet",
    "take amber",
    "go north",
    "examine altar",
    "take amulet",
    "take amber",
    "go north",
    "examine altar",
    "say abracadabra",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine altar",
    "take amber",
    "take amulet",
    "say abracadabra",
    "go north",
    "examine altar",
    "take amber",
    "take amulet",
    "take amber",
    "examine altar",
    "go north",
    "take amulet",
    "go north",
    "examine altar",
    "take amber",
    "abracadab",
    "take amulet",
    "examine altar",
    "take amber",
    "abracadab",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "abracadab",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "abracadab",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "abracadab",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "abracadab",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "abracadab",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take amber",
    "go north",
    "examine anaconda",
    "take amulet",
    "take amber",
    "go north",
    "examine anaconda",
    "unlock door",
    "take amulet",
    "take amber",
    "go north",
    "unlock door",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "examine anaconda",
    "take amber",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "unlock door",
    "go north",
    "take amber",
    "examine anaconda",
    "take amulet",
    "go north",
    "unlock door",
    "take amber",
    "examine anaconda",
    "take amulet",
    "go north",
    "examine anaconda",
    "take amber",
    "take adamant",
    "take amulet",
    "go north",
    "take amber",
    "take adamant",
    "examine anaconda",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amber",
    "take adamant",
    "examine anaconda",
    "go north",
    "examine altar",
    "take adamant",
    "examine anaconda",
    "go north",
    "examine altar",
    "take amulet",
    "take amulet",
    "examine amulet",
    "go north",
    "examine altar",
    "take adamant",
    "take amulet",
    "examine amulet",
    "go north",
    "take adamant",
    "examine altar",
    "take amulet",
    "examine amulet",
    "go north",
    "take adamant",
    "examine altar",
    "take amulet",
    "examine amulet",
    "go north",
    "take adamant",
    "examine altar",
    "take amulet",
    "examine amulet",
    "go north",
    "take adamant",
    "examine altar",
    "take amulet",
    "examine amulet",
    "go north",
    "take adamant",
    "examine altar",
    "take amulet",
    "examine amulet",
    "go north",
    "take adamant",
    "examine altar",
    "take amulet",
    "go north",
    "take adamant",
    "examine altar",
    "say abra",
    "take amulet",
    "say abra",
    "examine altar",
    "go north",
    "take adamant",
    "take amulet",
    "examine altar",
    "go north",
    "take adamant",
    "take amulet",
    "examine altar",
    "go north",
    "take adamant",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "go north",
    "take adamant",
    "examine anaconda",
    "take amulet",
    "examine altar",
    "take adamant",
    "examine anaconda",
    "go north",
    "take amulet",
    "examine altar",
    "take adamant",
    "go north",
    "examine anaconda",
    "take amulet",
    "take adamant",
    "examine altar",
    "go north",
    "examine anaconda",
    "take amulet",
    "take adamant",
    "examine altar",
    "go north",
    "examine anaconda",
    "examine altar",
    "take adamant",
    "go north",
    "examine anaconda",
    "take amulet",
    "take adamant",
    "take amulet",
    "go north",
    "examine anaconda",
    "examine altar",
    "take amulet",
    "examine amulet",
    "go north",
    "examine altar",
    "pray",
    "take amulet",
    "pray",
    "go north",
    "examine altar",
    "examine amulet",
    "take amulet",
    "pray",
    "go north",
    "examine altar",
    "examine amulet",
    "examine altar",
    "take amulet",
    "pray",
    "go north",
    "examine amulet",
    "take amulet",
    "examine amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "examine altar",
    "pray",
    "take amulet",
    "wear amulet",
    "go north",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "go north",
    "take amulet",
    "wear amulet",
    "go north",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take offerings",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take offerings",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take offerings",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take offerings",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "take offerings",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take offerings",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take offerings",
    "wear amulet",
    "go north",
    "examine altar",
    "examine amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take offerings",
    "wear amulet",
    "examine altar",
    "go north",
    "examine cave",
    "examine altar",
    "take offerings",
    "wear amulet",
    "go north",
    "examine cave",
    "take offerings",
    "wear amulet",
    "go north",
    "examine cave",
    "examine altar",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take offerings",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take offerings",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "take offerings",
    "go north",
    "take amulet",
    "wear amulet",
    "take offerings",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "go north",
    "examine altar",
    "pray",
    "take offerings",
    "wear amulet",
    "go north",
    "examine altar",
    "pray",
    "take offerings",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take offerings",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine amulet",
    "examine amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "wear amulet",
    "pray",
    "examine altar",
    "go north",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take agate",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine amulet",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine amulet",
    "examine altar",
    "examine altar",
    "pray",
    "wear amulet",
    "go north",
    "examine amulet",
    "pray",
    "wear amulet",
    "go north",
    "examine amulet",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "pray",
    "take amulet",
    "wear amulet",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "examine altar",
    "go north",
    "pray",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "examine altar",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "look",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "look",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take adamant",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "wear amulet",
    "pray",
    "go north",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray",
    "examine altar",
    "take key",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "wear amulet",
    "pray at altar",
    "take key",
    "examine altar",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "wear amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar",
    "take amulet",
    "pray at altar",
    "take key",
    "go east",
    "examine altar"
];

async function test() {
    console.log('=' .repeat(60));
    console.log(' ACHETON: Z2JS ENGINE TEST');
    console.log('=' .repeat(60));
    console.log(`Running ${commands.length} commands\n`);

    const m = createZMachine();
    let outputBuffer = '';
    let allOutput = '';

    m.outputCallback = (text) => {
        outputBuffer += text;
        allOutput += text;
    };

    let cmdIndex = 0;

    // Progress tracking
    let lastProgressReport = 0;

    function showProgress() {
        if (cmdIndex - lastProgressReport >= 30) {
            console.log(`--- Progress: ${cmdIndex}/${commands.length} commands ---`);
            lastProgressReport = cmdIndex;
        }
    }

    return new Promise((resolve, reject) => {
        function feedNextCommand() {
            if (cmdIndex >= commands.length) {
                console.log('\n--- All commands executed ---\n');
                console.log('FINAL OUTPUT:');
                console.log(allOutput.slice(-2000));

                // Try to extract score
                const scoreMatch = allOutput.match(/(\d+)\s+(?:out of|\/)\s*(\d+)/i);
                if (scoreMatch) {
                    console.log(`\nFinal Score: ${scoreMatch[1]}/${scoreMatch[2]} points`);
                }

                // Check for victory
                if (allOutput.match(/\*\*\* You have won \*\*\*|You have won|Victory|Congratulations/i)) {
                    console.log('\n✓ VICTORY: Game completed!');
                }

                resolve({ success: true, output: allOutput });
                return;
            }

            showProgress();

            const cmd = commands[cmdIndex];
            cmdIndex++;

            if (m.inputCallback) {
                outputBuffer = '';
                m.inputCallback(cmd);
                setTimeout(feedNextCommand, 5);
            } else if (m.finished) {
                console.log('\n!!! Game finished early');
                console.log('Final output:');
                console.log(outputBuffer.slice(-500));
                resolve({ success: true, output: allOutput });
            } else {
                setTimeout(feedNextCommand, 10);
            }
        }

        process.on('uncaughtException', (err) => {
            console.error('\nError:', err.message);
            console.error('Command index:', cmdIndex);
            if (cmdIndex > 0) {
                console.error('Last command:', commands[cmdIndex - 1]);
            }
            reject(err);
        });

        try {
            m.run();
            setTimeout(feedNextCommand, 50);
        } catch (e) {
            console.error('Failed to start game:', e.message);
            reject(e);
        }
    });
}

test()
    .then((result) => {
        console.log('\n' + '=' .repeat(60));
        console.log(' TEST COMPLETE');
        console.log('=' .repeat(60));
        process.exit(0);
    })
    .catch((err) => {
        console.error('\nTest failed:', err);
        process.exit(1);
    });
