#!/usr/bin/env node
/**
 * Smart test for enchanter with z2js
 *
 * Handles random events (combat, thief, grue, etc.)
 * Commands: 800
 */

const { createZMachine } = require('./enchanter_z2js.js');

// Suppress z2js noise ("[Z-Machine execution stopped]")
const originalError = console.error;
console.error = (...args) => {
    const msg = args.join(' ');
    if (!msg.includes('Z-Machine execution stopped')) {
        originalError.apply(console, args);
    }
};

const commands = [
    "n",
    "s",
    "e",
    "w",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "u",
    "d",
    "ne",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "nw",
    "se",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "sw",
    "in",
    "out",
    "n",
    "s",
    "e",
    "open window",
    "open door",
    "enter",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "s",
    "e",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "nw",
    "se",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "sw",
    "out",
    "n",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "north",
    "south",
    "east",
    "west",
    "exit",
    "enter chained",
    "enter wiser",
    "enter trees",
    "enter far",
    "enter book",
    "enter shrouded",
    "enter more",
    "enter release",
    "enter tower",
    "enter seen",
    "enter recognizable",
    "enter off",
    "enter rights",
    "enter pale",
    "enter girdle",
    "enter cretin",
    "enter enters",
    "enter their",
    "enter shack",
    "enter textures",
    "enter mysterious",
    "enter rolling",
    "enter fiction",
    "enter distant",
    "enter stretches",
    "enter squat",
    "enter inc",
    "enter eastern",
    "enter even",
    "enter hand",
    "exit chained",
    "exit wiser",
    "exit trees",
    "exit far",
    "exit book",
    "exit shrouded",
    "exit more",
    "exit release",
    "exit tower",
    "exit seen",
    "exit recognizable",
    "exit off",
    "exit rights",
    "exit pale",
    "exit girdle",
    "exit cretin",
    "exit enters",
    "exit their",
    "exit shack",
    "exit textures",
    "exit mysterious",
    "exit rolling",
    "exit fiction",
    "exit distant",
    "exit stretches",
    "exit squat",
    "exit inc",
    "exit eastern",
    "exit even",
    "exit hand",
    "climb chained",
    "climb wiser",
    "climb trees",
    "climb far",
    "climb book",
    "climb shrouded",
    "climb more",
    "climb release",
    "climb tower",
    "climb seen",
    "climb recognizable",
    "climb off",
    "climb rights",
    "climb pale",
    "climb girdle",
    "climb cretin",
    "climb enters",
    "climb their",
    "climb shack",
    "climb textures",
    "climb mysterious",
    "climb rolling",
    "climb fiction",
    "climb distant",
    "climb stretches",
    "climb squat",
    "climb inc",
    "climb eastern",
    "climb even",
    "climb hand",
    "open chained",
    "open wiser",
    "open trees",
    "open far",
    "open book",
    "open shrouded",
    "open more",
    "open release",
    "open tower",
    "open seen",
    "open recognizable",
    "open off",
    "open rights",
    "open pale",
    "open girdle",
    "open cretin",
    "open enters",
    "open their",
    "open shack",
    "open textures",
    "open mysterious",
    "open rolling",
    "open fiction",
    "open distant",
    "open stretches",
    "open squat",
    "open inc",
    "open eastern",
    "open even",
    "open hand",
    "close chained",
    "close wiser",
    "close trees",
    "close far",
    "close book",
    "close shrouded",
    "close more",
    "close release",
    "close tower",
    "close seen",
    "close recognizable",
    "close off",
    "close rights",
    "close pale",
    "close girdle",
    "close cretin",
    "close enters",
    "close their",
    "close shack",
    "close textures",
    "close mysterious",
    "close rolling"
];

// Random event patterns to detect
const randomEvents = [
    { id: "thief_encounter", name: "Thief", pattern: /thief|someone carrying a large bag|nasty knife|stiletto/i, checkItem: "sword" },
    { id: "troll_encounter", name: "Troll", pattern: /troll|nasty troll|dangerous troll/i, checkItem: "sword" },
    { id: "grue_warning", name: "Grue", pattern: /eaten by a grue|lurking grue|grue is|pitch black|dark\\..*eaten/i, checkItem: "lamp" },
    { id: "combat_attack", name: "Combat", pattern: /attacks you|strikes at you|swings at you|lunges at you|hits you/i, checkItem: "sword" },
    { id: "cyclops_encounter", name: "Cyclops", pattern: /cyclops|one-eyed giant/i, checkItem: null }
];

// Responses for each event type
const eventResponses = {
    "thief_encounter": {"has_sword": ["kill thief with sword", "attack thief with sword"], "default": ["drop all", "wait", "wait", "wait", "take all"]},
    "troll_encounter": {"has_sword": ["kill troll with sword", "attack troll"], "default": ["flee", "run", "retreat"]},
    "grue_warning": {"has_lamp": ["turn on lamp", "light lamp"], "default": ["go back", "retreat", "flee"]},
    "combat_attack": {"has_sword": ["kill attacker with sword", "attack", "fight"], "default": ["flee", "run"]},
    "cyclops_encounter": {"default": ["give lunch to cyclops", "say odysseus", "odysseus", "ulysses"]}
};

async function test() {
    console.log('='.repeat(60));
    console.log(' ENCHANTER: SMART Z2JS TEST');
    console.log('='.repeat(60));
    console.log(`Running ${commands.length} commands (with random event handling)\n`);

    const m = createZMachine();
    let outputBuffer = '';
    let allOutput = '';
    let inventory = new Set();  // Track inventory for conditional responses

    m.outputCallback = (text) => {
        outputBuffer += text;
        allOutput += text;

        // Track inventory changes
        if (/you.*(?:take|get|pick up)/i.test(text)) {
            const itemMatch = text.match(/(?:take|get|pick up)\s+(?:the\s+)?([\w\s]+)/i);
            if (itemMatch) inventory.add(itemMatch[1].toLowerCase().trim());
        }
        if (/taken/i.test(text) && outputBuffer.length < 50) {
            // Short "Taken." response - item from last command
        }
    };

    let cmdIndex = 0;
    let eventCommandsQueue = [];  // Commands to handle current event
    let handlingEvent = false;
    let eventsHandled = 0;
    let lastProgressReport = 0;

    function checkForRandomEvent(output) {
        for (const event of randomEvents) {
            if (event.pattern.test(output)) {
                return event;
            }
        }
        return null;
    }

    function getEventResponse(event) {
        const responses = eventResponses[event.id];
        if (!responses) return [];

        // Check if we have the required item for special response
        if (event.checkItem && inventory.has(event.checkItem)) {
            const key = `has_${event.checkItem}`;
            if (responses[key]) return [...responses[key]];
        }

        return responses.default ? [...responses.default] : [];
    }

    function showProgress() {
        if (cmdIndex - lastProgressReport >= 30) {
            console.log(`--- Progress: ${cmdIndex}/${commands.length} commands (events handled: ${eventsHandled}) ---`);
            lastProgressReport = cmdIndex;
        }
    }

    return new Promise((resolve, reject) => {
        function feedNextCommand() {
            // First, check if we detected a random event in last output
            if (!handlingEvent) {
                const event = checkForRandomEvent(outputBuffer);
                if (event) {
                    console.log(`\n>>> RANDOM EVENT: ${event.name} detected!`);
                    eventCommandsQueue = getEventResponse(event);
                    if (eventCommandsQueue.length > 0) {
                        handlingEvent = true;
                        eventsHandled++;
                        console.log(`    Responding with: ${eventCommandsQueue[0]}`);
                    }
                }
            }

            // Handle event commands first
            if (handlingEvent && eventCommandsQueue.length > 0) {
                const eventCmd = eventCommandsQueue.shift();
                if (eventCommandsQueue.length === 0) {
                    handlingEvent = false;  // Done with this event
                }

                if (m.inputCallback) {
                    outputBuffer = '';
                    m.inputCallback(eventCmd);
                    setTimeout(feedNextCommand, 5);
                    return;
                }
            }

            // Normal command processing
            if (cmdIndex >= commands.length) {
                console.log('\n--- All commands executed ---');
                console.log(`Events handled: ${eventsHandled}\n`);
                console.log('FINAL OUTPUT (last 1500 chars):');
                console.log(allOutput.slice(-1500));

                // Extract score
                const scoreMatch = allOutput.match(/(\d+)\s*(?:out of|\/)\s*(\d+)/i);
                if (scoreMatch) {
                    console.log(`\nFinal Score: ${scoreMatch[1]}/${scoreMatch[2]} points`);
                }

                // Check victory
                if (/\*\*\* You have won \*\*\*|You have won|Victory|Congratulations/i.test(allOutput)) {
                    console.log('\n✓ VICTORY: Game completed!');
                }

                resolve({ success: true, output: allOutput, eventsHandled });
                return;
            }

            showProgress();

            const cmd = commands[cmdIndex];
            cmdIndex++;

            // Track take commands for inventory
            if (/^(?:take|get|pick up)\s+/i.test(cmd)) {
                const itemMatch = cmd.match(/^(?:take|get|pick up)\s+(?:the\s+)?(.+)/i);
                if (itemMatch) inventory.add(itemMatch[1].toLowerCase().trim());
            }

            if (m.inputCallback) {
                outputBuffer = '';
                m.inputCallback(cmd);
                setTimeout(feedNextCommand, 5);
            } else if (m.finished) {
                console.log('\n!!! Game finished early');
                console.log('Final output:', outputBuffer.slice(-500));
                resolve({ success: true, output: allOutput, eventsHandled });
            } else {
                setTimeout(feedNextCommand, 10);
            }
        }

        process.on('uncaughtException', (err) => {
            console.error('\nError:', err.message);
            console.error('Command index:', cmdIndex);
            if (cmdIndex > 0) console.error('Last command:', commands[cmdIndex - 1]);
            reject(err);
        });

        try {
            m.run();
            setTimeout(feedNextCommand, 50);
        } catch (e) {
            console.error('Failed to start:', e.message);
            reject(e);
        }
    });
}

test()
    .then((result) => {
        console.log('\n' + '='.repeat(60));
        console.log(` TEST COMPLETE - Events: ${result.eventsHandled}`);
        console.log('='.repeat(60));
        process.exit(0);
    })
    .catch((err) => {
        console.error('\nTest failed:', err);
        process.exit(1);
    });
