#!/usr/bin/env node
/**
 * Test enchanter with z2js
 *
 * Generated from solution JSON file
 * Commands: 800
 */

const { createZMachine } = require('./enchanter_z2js.js');

const commands = [
    "n",
    "s",
    "e",
    "w",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "u",
    "d",
    "ne",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "nw",
    "se",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "sw",
    "in",
    "out",
    "n",
    "s",
    "e",
    "open window",
    "open door",
    "enter",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "s",
    "e",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "nw",
    "se",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "sw",
    "out",
    "n",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "n",
    "s",
    "e",
    "open window",
    "open door",
    "enter",
    "in",
    "open gate",
    "move rug",
    "open trapdoor",
    "open trap door",
    "move carpet",
    "pull lever",
    "push button",
    "open chest",
    "open box",
    "open coffin",
    "down",
    "up",
    "climb down",
    "climb up",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "take all",
    "get all",
    "take lamp",
    "take lantern",
    "take sword",
    "take key",
    "take keys",
    "take bottle",
    "take food",
    "take garlic",
    "take knife",
    "take rope",
    "turn on lamp",
    "light lamp",
    "turn on lantern",
    "light lantern",
    "n",
    "s",
    "e",
    "w",
    "u",
    "d",
    "ne",
    "nw",
    "se",
    "sw",
    "out",
    "north",
    "south",
    "east",
    "west",
    "exit",
    "enter chained",
    "enter wiser",
    "enter trees",
    "enter far",
    "enter book",
    "enter shrouded",
    "enter more",
    "enter release",
    "enter tower",
    "enter seen",
    "enter recognizable",
    "enter off",
    "enter rights",
    "enter pale",
    "enter girdle",
    "enter cretin",
    "enter enters",
    "enter their",
    "enter shack",
    "enter textures",
    "enter mysterious",
    "enter rolling",
    "enter fiction",
    "enter distant",
    "enter stretches",
    "enter squat",
    "enter inc",
    "enter eastern",
    "enter even",
    "enter hand",
    "exit chained",
    "exit wiser",
    "exit trees",
    "exit far",
    "exit book",
    "exit shrouded",
    "exit more",
    "exit release",
    "exit tower",
    "exit seen",
    "exit recognizable",
    "exit off",
    "exit rights",
    "exit pale",
    "exit girdle",
    "exit cretin",
    "exit enters",
    "exit their",
    "exit shack",
    "exit textures",
    "exit mysterious",
    "exit rolling",
    "exit fiction",
    "exit distant",
    "exit stretches",
    "exit squat",
    "exit inc",
    "exit eastern",
    "exit even",
    "exit hand",
    "climb chained",
    "climb wiser",
    "climb trees",
    "climb far",
    "climb book",
    "climb shrouded",
    "climb more",
    "climb release",
    "climb tower",
    "climb seen",
    "climb recognizable",
    "climb off",
    "climb rights",
    "climb pale",
    "climb girdle",
    "climb cretin",
    "climb enters",
    "climb their",
    "climb shack",
    "climb textures",
    "climb mysterious",
    "climb rolling",
    "climb fiction",
    "climb distant",
    "climb stretches",
    "climb squat",
    "climb inc",
    "climb eastern",
    "climb even",
    "climb hand",
    "open chained",
    "open wiser",
    "open trees",
    "open far",
    "open book",
    "open shrouded",
    "open more",
    "open release",
    "open tower",
    "open seen",
    "open recognizable",
    "open off",
    "open rights",
    "open pale",
    "open girdle",
    "open cretin",
    "open enters",
    "open their",
    "open shack",
    "open textures",
    "open mysterious",
    "open rolling",
    "open fiction",
    "open distant",
    "open stretches",
    "open squat",
    "open inc",
    "open eastern",
    "open even",
    "open hand",
    "close chained",
    "close wiser",
    "close trees",
    "close far",
    "close book",
    "close shrouded",
    "close more",
    "close release",
    "close tower",
    "close seen",
    "close recognizable",
    "close off",
    "close rights",
    "close pale",
    "close girdle",
    "close cretin",
    "close enters",
    "close their",
    "close shack",
    "close textures",
    "close mysterious",
    "close rolling"
];

async function test() {
    console.log('=' .repeat(60));
    console.log(' ENCHANTER: Z2JS ENGINE TEST');
    console.log('=' .repeat(60));
    console.log(`Running ${commands.length} commands\n`);

    const m = createZMachine();
    let outputBuffer = '';
    let allOutput = '';

    m.outputCallback = (text) => {
        outputBuffer += text;
        allOutput += text;
    };

    let cmdIndex = 0;

    // Progress tracking
    let lastProgressReport = 0;

    function showProgress() {
        if (cmdIndex - lastProgressReport >= 30) {
            console.log(`--- Progress: ${cmdIndex}/${commands.length} commands ---`);
            lastProgressReport = cmdIndex;
        }
    }

    return new Promise((resolve, reject) => {
        function feedNextCommand() {
            if (cmdIndex >= commands.length) {
                console.log('\n--- All commands executed ---\n');
                console.log('FINAL OUTPUT:');
                console.log(allOutput.slice(-2000));

                // Try to extract score
                const scoreMatch = allOutput.match(/(\d+)\s+(?:out of|\/)\s*(\d+)/i);
                if (scoreMatch) {
                    console.log(`\nFinal Score: ${scoreMatch[1]}/${scoreMatch[2]} points`);
                }

                // Check for victory
                if (allOutput.match(/\*\*\* You have won \*\*\*|You have won|Victory|Congratulations/i)) {
                    console.log('\n✓ VICTORY: Game completed!');
                }

                resolve({ success: true, output: allOutput });
                return;
            }

            showProgress();

            const cmd = commands[cmdIndex];
            cmdIndex++;

            if (m.inputCallback) {
                outputBuffer = '';
                m.inputCallback(cmd);
                setTimeout(feedNextCommand, 5);
            } else if (m.finished) {
                console.log('\n!!! Game finished early');
                console.log('Final output:');
                console.log(outputBuffer.slice(-500));
                resolve({ success: true, output: allOutput });
            } else {
                setTimeout(feedNextCommand, 10);
            }
        }

        process.on('uncaughtException', (err) => {
            console.error('\nError:', err.message);
            console.error('Command index:', cmdIndex);
            if (cmdIndex > 0) {
                console.error('Last command:', commands[cmdIndex - 1]);
            }
            reject(err);
        });

        try {
            m.run();
            setTimeout(feedNextCommand, 50);
        } catch (e) {
            console.error('Failed to start game:', e.message);
            reject(e);
        }
    });
}

test()
    .then((result) => {
        console.log('\n' + '=' .repeat(60));
        console.log(' TEST COMPLETE');
        console.log('=' .repeat(60));
        process.exit(0);
    })
    .catch((err) => {
        console.error('\nTest failed:', err);
        process.exit(1);
    });
